export function buildIterateWorkflowScript(): string {
	return [
		"export const meta = { name: 'iterate_refine', description: 'Refine an existing task with a fixed lightweight iteration workflow' };",
		"",
		"const instructions = typeof args?.instructions === 'string' ? args.instructions.trim() : '';",
		"if (!instructions) throw new Error('iterate instructions are required');",
		"",
		"const previousTaskId = typeof args?.previousTaskId === 'string' && args.previousTaskId ? args.previousTaskId : 'unknown';",
		"const previousResult = args?.previousResult ?? null;",
		"",
		"function readSummary(value) {",
		"  if (!value) return '';",
		"  if (typeof value === 'string') return value.trim();",
		"  if (typeof value !== 'object' || Array.isArray(value)) return '';",
		"  if (typeof value.summary === 'string' && value.summary.trim()) return value.summary.trim();",
		"  if (value.artifact && typeof value.artifact === 'object' && !Array.isArray(value.artifact)) {",
		"    if (typeof value.artifact.summary === 'string' && value.artifact.summary.trim()) return value.artifact.summary.trim();",
		"  }",
		"  return '';",
		"}",
		"",
		"const previousImplementationSummary =",
		"  readSummary(previousResult?.refined) ||",
		"  readSummary(previousResult?.implementation) ||",
		"  readSummary(previousResult?.candidate) ||",
		"  readSummary(previousResult);",
		"",
		"const previousValidationSummary =",
		"  readSummary(previousResult?.validation) ||",
		"  readSummary(previousResult?.review) ||",
		"  '';",
		"",
		"const previousResultKeys = previousResult && typeof previousResult === 'object' && !Array.isArray(previousResult)",
		"  ? Object.keys(previousResult).slice(0, 10).join(', ')",
		"  : '';",
		"",
		"phase('Refine');",
		"const refined = await implement(",
		"  `Refine the current task in the existing workspace. This is an iteration on a previous task, so do not redesign the whole workflow or restart from scratch unless the new instructions explicitly require that.",
		"",
		"Authoritative iteration instructions:",
		"${instructions}",
		"",
		"Previous task: ${previousTaskId}",
		"Previous result keys: ${previousResultKeys || '(none)'}",
		"Previous implementation summary:",
		"${previousImplementationSummary || '(none)'}",
		"",
		"Previous validation/review summary:",
		"${previousValidationSummary || '(none)'}",
		"",
		"Rules:",
		"- treat the new iteration instructions as authoritative over the previous attempt",
		"- prefer the smallest safe patch that satisfies the updated direction",
		"- read only what you need from the repository",
		"- keep the work focused; do not add extra redesign or broad cleanup unless explicitly required",
		"- update only the focused tests or checks needed for confidence`,",
		"  {",
		"    role: 'developer',",
		"    guidance:",
		"      'Use a quick iteration path: refine the implementation directly, preserve useful parts of the previous attempt when still valid, and keep the diff minimal.'",
		"  }",
		");",
		"",
		"phase('Validate');",
		"const validation = await testChange(refined, {",
		"  role: 'tester',",
		"  guidance:",
		"    `Validate only the refined change. Run the most focused relevant checks for the iteration instructions above, report what you ran, and state clearly whether the authoritative instructions were satisfied. If you return structured output, use issues only for blocking validation failures and put non-blocking notes in warnings.`",
		"});",
		"",
		"return { refined, validation };",
	].join("\n");
}
