// Portions of this file are derived from pi-dynamic-workflows
// (https://github.com/Michaelliv/pi-dynamic-workflows), MIT licensed.

export const WORKFLOW_AUTHOR_PROMPT_SNIPPET =
	"Write a deterministic JavaScript workflow. Required script header: export const meta = { name: 'short_snake_case', description: 'non-empty description' }. meta.phases is optional documentation; live progress is driven by phase(title).";

export const WORKFLOW_AUTHOR_GUIDELINES = [
	"Output one raw JavaScript string. First statement: export const meta = { name, description }. Plain JS only, no imports/TypeScript/Date.now()/Math.random().",
	"Available globals: agent(prompt, opts), parallel(thunks), pipeline(items, ...stages), phase(title), log(message), request_human(request), args, cwd, budget.",
	"Every agent() must include a unique short label. Use schema for structured output. Direct agent() failures fail the workflow; parallel()/pipeline() failures return null.",
	"Assess task complexity:",
	"  simple (one function/CLI change, bug fix): single dev agent, no phases. Dev does TDD end-to-end.",
	"  medium (multi-file, feature improvement): dev agent + optional read-only review agent. If review needs_fix, loop back to dev once max.",
	"  large (cross-module, architecture): optional read-only fan-out for analysis, then sequential code-changing agents, then review.",
	"Code-changing agents use { label, agentType: 'dev', isolation: 'worktree', schema }. Prompt includes task, relevant files, targeted test command, TDD instruction. Do not include line numbers or code snippets — the agent reads code itself.",
	"Review agents use { label, agentType: 'review', isolation: 'worktree', schema }. Review is read-only, does not modify files.",
	"All agents in the same task share one task-scoped worktree. Run code-changing agents sequentially, never in parallel.",
	"Do not read existing workflow files. Generate from scratch. Return compact JSON; always await agent()/parallel()/pipeline().",
	"agent() prompts must use backtick template literals (not single quotes) when they span multiple lines. Single-line prompts may use single quotes.",
] as const;

export function buildWorkflowAuthorPrompt(taskPrompt: string): string {
	return [
		"Write a kanade workflow script for the following task.",
		WORKFLOW_AUTHOR_PROMPT_SNIPPET,
		"Guidelines:",
		...WORKFLOW_AUTHOR_GUIDELINES.map((line) => `- ${line}`),
		"",
		"Example (simple task):",
		"export const meta = { name: 'fix_bug', description: 'Fix null pointer in login' };",
		"",
		"phase('Implement');",
		"",
		"return await agent(`Fix the null pointer error in src/auth/login.ts. Use TDD: add a test first, then fix. Run: npx vitest run src/auth/login.test.ts`, {",
		"  label: 'fix login bug',",
		"  agentType: 'dev',",
		"  isolation: 'worktree',",
		"  schema: { type: 'object', properties: { status: { type: 'string', enum: ['done', 'blocked'] }, summary: { type: 'string' }, filesChanged: { type: 'array', items: { type: 'string' } }, testsRun: { type: 'string' } }, required: ['status', 'summary', 'filesChanged', 'testsRun'] }",
		"});",
		"",
		"Example (medium task with review):",
		"export const meta = { name: 'refactor_api', description: 'Refactor user API endpoints' };",
		"",
		"phase('Implement');",
		"const dev = await agent('Refactor user API in src/api/users.ts. Use TDD. Run: npx vitest run src/api/users.test.ts', {",
		"  label: 'refactor users', agentType: 'dev', isolation: 'worktree',",
		"  schema: { type: 'object', properties: { status: { type: 'string', enum: ['done', 'blocked'] }, summary: { type: 'string' }, filesChanged: { type: 'array', items: { type: 'string' } }, testsRun: { type: 'string' } }, required: ['status', 'summary', 'filesChanged', 'testsRun'] }",
		"});",
		"",
		"phase('Review');",
		"const review = await agent('Review the refactored user API for correctness and test coverage.', {",
		"  label: 'review users', agentType: 'review', isolation: 'worktree',",
		"  schema: { type: 'object', properties: { status: { type: 'string', enum: ['approved', 'needs_fix'] }, summary: { type: 'string' }, issues: { type: 'array', items: { type: 'string' } } }, required: ['status', 'summary'] }",
		"});",
		"",
		"if (review.status === 'needs_fix') {",
		"  phase('Fix');",
		"  const fix = await agent(`Fix these issues: ${review.issues.join(', ')}. Run: npx vitest run src/api/users.test.ts`, {",
		"    label: 'fix users', agentType: 'dev', isolation: 'worktree',",
		"    schema: { type: 'object', properties: { status: { type: 'string', enum: ['done', 'blocked'] }, summary: { type: 'string' }, filesChanged: { type: 'array', items: { type: 'string' } }, testsRun: { type: 'string' } }, required: ['status', 'summary', 'filesChanged', 'testsRun'] }",
		"  });",
		"  return { dev, review, fix };",
		"}",
		"",
		"return { dev, review };",
		"",
		"Task:",
		taskPrompt,
		"",
		"Output contract:",
		"- Your final action MUST be a structured_output tool call.",
		"- The structured_output arguments must contain a 'script' field with the complete JavaScript workflow string.",
		"- Do not emit prose or markdown. Call structured_output exactly once with the script.",
	].join("\n");
}
